sudo: required
dist: trusty
language: node_js
node_js:
  - "9.11.1"
cache:
  - node_modules
install:
  - npm install
script:
  - npm run eslint-check
  - npm run test
  - npm run build:app
  - npm run build:fetival-data
