version: 2
jobs:
  build:
    docker:
      - image: circleci/node:9.11.1

    working_directory: ~/repo

    steps:
      - checkout
      - run: npm install
      - run: node tools/builder-festivalData.js
      - run: webpack
      - run: npm run test
      - run: npm run eslint-check
