version: 2
jobs:
  build:
    docker:
      - image: circleci/node:9.11.1

    steps:
      - checkout
      - run:
          name: 'Install dependencies'
          command: npm install
      - run:
          name: 'Check code corectness'
          command: npm run eslint-check

      - run:
          name: 'Run tests'
          command: npm run test
