#!/bin/bash

set -e

symlink() {
 if [[ -d .git/hooks  &&  $NODE_ENV != "test" ]]; then
   ln -s -f ../../hooks/"$1" .git/hooks/"$1"
   chmod +x .git/hooks/"$1"
   tput setaf 6
   printf "%s\n" "../../hooks/$1 ~> .git/hooks/$1"
   tput sgr0
 fi
}

symlink "pre-commit"
